<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace TNTFrance\Event\Module\Base;

/**
 * Class TNTFranceEvents
 * @package TNTFrance\Event\Module\Base
 * @author TheliaStudio
 */
class TNTFranceEvents
{
    const TNT_FRANCE__CREATE = "action.tnt_france_.create";
    const TNT_FRANCE__UPDATE = "action.tnt_france_.update";
    const TNT_FRANCE__DELETE = "action.tnt_france_.delete";
}
