<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace TNTFrance\Form;

use TNTFrance\TNTFrance;
use TNTFrance\Form\Base\TNTFranceConfigForm as BaseTNTFranceConfigForm;

/**
 * Class TNTFranceConfigForm
 * @package TNTFrance\Form\Base
 */
class TNTFranceConfigForm extends BaseTNTFranceConfigForm
{
    public function getTranslationKeys()
    {
        return array(
            "enabled" => $this->translator->trans("Do you want to activate TNT Express National", [], TNTFrance::MESSAGE_DOMAIN),
            "mode_production" => $this->translator->trans("Use the production mode ?", [], TNTFrance::MESSAGE_DOMAIN),
            "account_number" => $this->translator->trans("Your myTNT Account Number", [], TNTFrance::MESSAGE_DOMAIN),
            "username" => $this->translator->trans("Your myTNT username", [], TNTFrance::MESSAGE_DOMAIN),
            "password" => $this->translator->trans("Password", [], TNTFrance::MESSAGE_DOMAIN),
            "use_individual" => $this->translator->trans("Use individual", [], TNTFrance::MESSAGE_DOMAIN),
            "use_enterprise" => $this->translator->trans("Use enterprise", [], TNTFrance::MESSAGE_DOMAIN),
            "use_depot" => $this->translator->trans("Use TNT depot", [], TNTFrance::MESSAGE_DOMAIN),
            "use_dropoffpoint" => $this->translator->trans("Use drop off point", [], TNTFrance::MESSAGE_DOMAIN),
            "products_enabled" => $this->translator->trans("List of available products", [], TNTFrance::MESSAGE_DOMAIN),
            "options_enabled" => $this->translator->trans("List of available options", [], TNTFrance::MESSAGE_DOMAIN),
            "regular_pickup" => $this->translator->trans("Regular pickup", [], TNTFrance::MESSAGE_DOMAIN),
            "sender_name" => $this->translator->trans("name", [], TNTFrance::MESSAGE_DOMAIN),
            "sender_address1" => $this->translator->trans("address 1", [], TNTFrance::MESSAGE_DOMAIN),
            "sender_address2" => $this->translator->trans("address 2", [], TNTFrance::MESSAGE_DOMAIN),
            "sender_zip_code" => $this->translator->trans("zip code", [], TNTFrance::MESSAGE_DOMAIN),
            "sender_city" => $this->translator->trans("City", [], TNTFrance::MESSAGE_DOMAIN),
            "contact_lastname" => $this->translator->trans("Contact last name", [], TNTFrance::MESSAGE_DOMAIN),
            "contact_firstname" => $this->translator->trans("Contact first name", [], TNTFrance::MESSAGE_DOMAIN),
            "contact_email" => $this->translator->trans("Contact email", [], TNTFrance::MESSAGE_DOMAIN),
            "contact_phone" => $this->translator->trans("Contact phnoe number", [], TNTFrance::MESSAGE_DOMAIN),
            "notification_emails" => $this->translator->trans("Notification emails", [], TNTFrance::MESSAGE_DOMAIN),
            "notification_success" => $this->translator->trans("Notification on successfull pick up", [], TNTFrance::MESSAGE_DOMAIN),
            "label_format" => $this->translator->trans("Print format, options", [], TNTFrance::MESSAGE_DOMAIN),
            "help.mode_production" => $this->translator->trans("if not checked the test mode will be used", [], TNTFrance::MESSAGE_DOMAIN),
            "help.notification_emails" => $this->translator->trans("List of emails (separated by a ,) that will be notified on pick up anomaly", [], TNTFrance::MESSAGE_DOMAIN),
            "free_shipping" => $this->translator->trans("Use free shipping", [], TNTFrance::MESSAGE_DOMAIN),
            "max_weight_package" => $this->translator->trans("Max weight per package (kg)", [], TNTFrance::MESSAGE_DOMAIN),
            "tracking_url" => $this->translator->trans("The URL to access to a parcel’s delivery status", [], TNTFrance::MESSAGE_DOMAIN),
            "help.tracking_url" => $this->translator->trans("%tracking-number% will be replaced by the real tracking number", [], TNTFrance::MESSAGE_DOMAIN),
        );
    }
}
