<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace TNTFrance\Event\Module;

use TNTFrance\Event\Module\Base\TNTFranceEvents as BaseTNTFranceEvents;

/**
 * Class TNTFranceEvents
 * @package TNTFrance\Event\Module
 * @author TheliaStudio
 */
class TNTFranceEvents extends BaseTNTFranceEvents
{
    const TNT_FRANCE_EXPORT = "action.tnt_france.export";
    const TNT_FRANCE_CREATE_EXPEDITION = "action.tnt_france.create_expedition";
    const TNT_FRANCE_PRINT_EXPEDITION = "action.tnt_france.print_expedition";
}
