<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace TNTFrance\Controller;

use TNTFrance\Controller\Base\TNTFranceConfigController as BaseTNTFranceConfigController;

/**
 * Class TNTFranceConfigController
 * @package TNTFrance\Controller
 */
class TNTFranceConfigController extends BaseTNTFranceConfigController
{
}
